modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="waystone_wings"
version="0.1.0"
displayName="Waystone Wings"
authors="Jam Femino"
description='''
Turns the Elytra into a Waystones progression component and rebuilds Waystones recipes around Create machinery, or the vanilla crafting table when Create is not installed.
'''

[[mixins]]
config="waystone_wings.mixins.json"

[[dependencies.waystone_wings]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"

[[dependencies.waystone_wings]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.waystone_wings]]
modId="create"
type="optional"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.waystone_wings]]
modId="waystones"
type="required"
versionRange="[21.1.45,)"
ordering="AFTER"
side="BOTH"

[[dependencies.waystone_wings]]
modId="balm"
type="required"
versionRange="[21.0.65,)"
ordering="AFTER"
side="BOTH"
